---
- hosts: all
  become: true
  roles:
    - docker

- hosts: elk
  become: true
  roles:
    - elk
    
- pause:
  minutes: 2

- hosts: webservers
  become: true
  roles:
    - web
    - filebeat
    - metricbeat