---
- hosts: all
  become: true
  roles:
    - docker

- hosts: elk
  become: true
  roles:
    - elk

- name: Pause for two minutes for Elk Container to execute
  pause:
    minutes: 2

- hosts: webservers
  become: true
  roles:
    - web
    - filebeat
    - metricbeat