---
- ansible.posix.sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present
    reload: yes

- name: download and launch a docker elk container
  docker_container:
    name: elk
    image: sebp/elk:761
    state: started
    published_ports:
    - 5601:5601
    - 9200:9200
    - 5044:5044

- name: Wait for Elk port 9200 to be open
  wait_for:
    host: 10.1.0.4
    port: 9200
    delay: 60
    state: drained