---
- name: Install Docker python module
  pip:
    name: docker
    state: present

- name: download and launch a docker web container
  docker_container:
    name: dvwa
    image: cyberxsecurity/dvwa
    state: started
    published_ports: 80:80